### ISSUE TITLE
Missing loci in the results

### ISSUE THREAD

**Issue by hanfu-bios** [seqcode/miniMDS#14]
Hi,

In my miniMDS results, some loci got deleted. For example, there are 250 loci on chromosome 1 in my original data, but in the output of the chr 1 structure, there are only 240 loci with 21 loci having missing coordinates. And I have no clue which loci remained and which were omitted. The deletion occurred in most of the chromosomes. I was wondering in what situation the deletion might happen or the coordinates cannot be estimated (appearing as missing values).
Thank you!

The command I used was 
`python ../miniMDS/minimds_inter.py -C 22 -n 5 -o res79b/K562res sc79B/K562 1000000 1000000`

Input files:
[miniMDS.zip](https://github.com/seqcode/miniMDS/files/2329378/miniMDS.zip)
Output files I got:
[miniMDSresult.zip](https://github.com/seqcode/miniMDS/files/2329403/miniMDSresult.zip)

**Comment by Lila14** [comment]
It looks like the missing datapoints aren't in the input intrachromosomal files. For example, the third line of the header of K562res_1_1mb_structure.tsv says that there is 0 offset in the indexing. So locus 122, which is missing, corresponds to the bin chr1:122Mb-123Mb. This bin doesn't appear in K562_1_1mb.bed. 

Most of the missing bins in your input correspond to low mappability regions, such as the centromere. If you're interested in these regions, you could try [mhic](https://github.com/yezhengSTAT/mHiC), which rescues multi-mapped reads.

**Comment by hanfu-bios** [comment]
Hi Lila,

Thank you for your reply. I have found the missing bins in my input files after I sent you the message. However, there are still inconsistencies with regard to the number of bins between the input and output. Take chromosome 1 for example - the input file has 250 bins in total including the missing section from 122Mb-143Mb - the output gives missing values for these loci. But leave these loci aside, the output has only 241 loci available including the NAN ones. 

Do you have any idea why the last 9 loci did not show up in the output results?

Thanks,
Han

**Comment by Lila14** [comment]
I'm not able to replicate your output using that command. I've attached the output I get for chr1. Can you make sure you have the latest version of miniMDS?
[K562res_1_1mb_structure.txt](https://github.com/seqcode/miniMDS/files/2384092/K562res_1_1mb_structure.txt)

**Comment by hanfu-bios** [comment]
I have updated to the latest version. The numbers of loci in most chromosomes are now consistent. But there are still some chromosomes which have one locus disappeared from the output. For example, the input for chromosome 2 had 244 loci but the output had 243 loci. Same for chromosome 4, 17, and 21.

**Comment by Lila14** [comment]
Can you make sure you've attached the correct input files? In the input files you gave me, chr2 doesn't have 244 loci. The starting genomic bin is 0-1000000 and the ending bin is 242000000-243000000.

**Comment by hanfu-bios** [comment]
If you count from 0 to 243, that would be 244 loci in total. But the output only contains loci from 0 to 242. So there is one missing.

**Comment by Lila14** [comment]
Loci are the same as bins. There's no data for 243,000,000, so it isn't
counted as a locus. So there are 243 loci.
