### ISSUE TITLE
TADs modeling

### ISSUE THREAD

**Issue by ahorvath** [seqcode/miniMDS#15]
What setting do you recommend for TAD (not more than three consecutive TADs for example) modeling with only a couple of hundreds (or less) points?
 
I use Hi-C and RNAPII S2 HiChIP data and I think miniMDS might give better results on actively transcribed regions using HiChIP (and I suppose HiChIP can't be used for whole chromosome modeling as it doesn't give any signal from not active regions/tads)

Thanks in advance.

**Comment by Lila14** [comment]
-p 0.01 and -m 0.01 will result in relatively few partitions. You can keep reducing these values until you get the approximate number of partitions you want. Note that miniMDS partitions don't correspond exactly to TADs, though they're similar. In the future we will add support for other TAD-calling algorithms.

**Comment by Lila14** [comment]
Please note that there have been some major updates. I recommend pulling the latest version of the code. Partitioned MDS is not default now, so you'll need to use the --partitioned option.

**Comment by ahorvath** [comment]
Thanks @Lila14 for your useful advice. I'll check it out.
