### ISSUE TITLE
example is not run

### ISSUE THREAD

**Issue by zhixuqiu** [seqcode/miniMDS#16]
bash fig10.sh 
usage: normalize.py [-h] [--chrom2 CHROM2] hic_id res chrom1 norm
normalize.py: error: the following arguments are required: norm

**Comment by zhixuqiu** [comment]
I added this arguments in your python script normalize.py.  it was also not run.

```
File "/home/qiuzx/software/installed_dir/miniconda2/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 860, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: 'GM12878_combined/10.0kb_resolution_intrachromosomal/chr1/MAPQGE30/chr1_10.0kb.KRnorm'

```

**Comment by Lila14** [comment]
Sorry, I've fixed the scripts now. Many still had old parameters. Let me know if there are further issues.

**Comment by zhixuqiu** [comment]
> Sorry, I've fixed the scripts now. Many still had old parameters. Let me know if there are further issues.

**OK, thanks. But I tried again. The script fig10.sh was also not implemented.** 

`FileNotFoundError: [Errno 2] No such file or directory: GM12878_combined/10.0kb_resolution_intrachromosomal/chr1/MAPQGE30/chr1_10.0kb.KRnorm`

**This error also existed in script "minimds_inter.py" . The error was from the function "get_res_string"  in script "tools.py". I have change it.** 

`res_kb = round(res/1000)
if res_kb < 1000:
		return str(res_kb) + "kb"
	else:
		return str(round(res_kb/1000)) + "mb"`

**But a new bug occured. I don't know how to correct it.**

` File "../normalize.py", line 26, in normalize
    norm1 = kr1[int(loc1)/res]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

**Comment by Lila14** [comment]
It looks the res variable in normalize.py is a float in your example. I'm not sure why this would happen, because the res argument is read as an int. Can you make sure you have the current version of normalize.py?

**Comment by zhixuqiu** [comment]
> It looks the res variable in normalize.py is a float in your example. I'm not sure why this would happen, because the res argument is read as an int. Can you make sure you have the current version of normalize.py?

Yes, I used the new normalize.py.  To correct res argument, I changed the tools.py.

**Comment by ahorvath** [comment]
Hi @Lila14,

I'd like to infer interchromosomal interactions. When running sh fig10.sh I got this error:

python ../minimds_inter.py --partitioned -l 100000 -p 0.01 -m 0.01 -o hic_data/GM12878_combined hic_data/GM12878_combined_interchromosomal hic_data/GM12878_combined 1000000 10000 

usage: minimds_inter.py [-h] [--partitioned] [-c C] [-C C] [-l L] [-p P]
                        [-m M] [-o O] [-r R] [-n N] [-a A] [-a2 A2]
                        prefix inter_res intra_res
....
minimds_inter.py: error: argument inter_res: invalid int value: 'hic_data/GM12878_combined'
[ahorvath@admin scripts]$ ls hic_data/GM12878_combined

Can you help me, please?

Bests,
Attila

**Comment by Lila14** [comment]
There are too many arguments. Notice that in addition to the optional
arguments, there are four positional arguments:
hic_data/GM12878_combined_interchromosomal hic_data/GM12878_combined
1000000 10000. There should be exactly three positional arguments: the
prefix of input files, the interchromosomal resolution, and the
intrachromosomal resolution.

**Comment by ahorvath** [comment]
Can you provide an example, please?

This was from fig10.sh

set -e

bash get_gm12878.sh 10000 0
bash get_gm12878.sh 100000 0
bash get_gm12878.sh 1000000 0
bash get_gm12878_inter.sh 1000000

python ../minimds_inter.py --partitioned -l 100000 -p 0.01 -m 0.01 -o hic_data/GM12878_combined hic_data/GM12878_combined_interchromosomal hic_data/GM12878_combined 1000000 10000
python fig10.py

Thanks in advance.

**Comment by Lila14** [comment]
Sorry for the late reply. I've pushed some changes that should fix fig10.sh. I haven't fully tested them, so let me know if there are any issues.

**Comment by Lila14** [comment]
fig10.sh seems to be working now. Please make sure you pull the latest code.
