### ISSUE TITLE
Cannot create 3D plot of multiple structures

### ISSUE THREAD

**Issue by yasunobumaeda** [seqcode/miniMDS#17]
I made five .tsv files.
SRv6tmp_1_150kb_structure.tsv
SRv6tmp_2_150kb_structure.tsv
SRv6tmp_3_150kb_structure.tsv
SRv6tmp_4_150kb_structure.tsv
SRv6tmp_5_150kb_structure.tsv

And also I made a multiple structures script file.
import data_tools
import plotting
chroms = (1, 2, 3, 4, 5)
structures = [data_tools.structure_from_file("SRv6tmp_{}_150kb_structure.tsv".format(chrom) for chrom in chroms)]
plotting.plot_structures_interactive(structures)

However, this script output error and not work.
Traceback (most recent call last):
  File "plot.py", line 4, in <module>
    structures = [data_tools.structure_from_file("SRv6tmp_{}_150kb_structure.tsv".format(chrom) for chrom in chroms)]
  File "/Applications/miniMDS/data_tools.py", line 288, in structure_from_file
    with open(path) as infile:
TypeError: expected str, bytes or os.PathLike object, not generator

I tested to run single chromosome structure script.
import data_tools
import plotting
structure = data_tools.structure_from_file("SRv6tmp_1_150kb_structure.tsv")
plotting.plot_structure_interactive(structure, color=(0,0.5,0.7), radius=0.01)

But it works well.

How to check the multiple structures?
if you have some ideas, please.

**Comment by Lila14** [comment]
Can you change 
`structures = [data_tools.structure_from_file("SRv6tmp_{}_150kb_structure.tsv".format(chrom) for chrom in chroms)]`

to 
`structures = [data_tools.structure_from_file("SRv6tmp_{}_150kb_structure.tsv".format(chrom)) for chrom in chroms]`

**Comment by yasunobumaeda** [comment]
Now it works.
Thanks a lot.
