### ISSUE TITLE
 input file

### ISSUE THREAD

**Issue by songxh1996** [seqcode/miniMDS#23]
hello：
The software you developed is fantastic, but I had trouble of input file.
I have got the result processed by hicpro, but I don't know how to deal with the input file (bed file) to get minimds.
best wishes

![1678785122401](https://user-images.githubusercontent.com/119746508/224952305-d96bd500-7ced-4ec7-9794-25b356e1cb3e.png)

**Comment by Lila14** [comment]
I've added a script to do this, based on my understanding of the results format described here: https://nservant.github.io/HiC-Pro/RESULTS.html#mapping-results

`python scripts/hicpro_to_bedpe.py [NAMES BED PATH] [MATRIX PATH] [OUTPUT BED PATH]`

[NAMES BED PATH] is the path to a BED file connecting genomic intervals to names, e.g.

>chr1   1    2    A
>chr2   1    2    B
>chr3   1    2    C

[MATRIX PATH] is the path to a sparse counts matrix file, e.g.
>A    B    10
>A    C   23
>B    C   24

[OUTPUT BED PATH] is the path where the output miniMDS input BED file will be written

**Comment by Lila14** [comment]
Note that hicpro produces fragment-level output. You'll probably want to run bin_bed.py to change to the desired resolution

`cd scripts`
`python bin_bed.py [input path] [resolution (bp)] [output path]`

**Comment by Lila14** [comment]
I've added some example data to scripts/hicpro. Now you can run the following example:

```
cd scripts/hicpro
python hicpro_to_bedpe.py HindIII_resfrag_hg19_downsampled.bed hic.matrix all.bed
cat all.bed | awk '$1 == "chr1" && $4 == "chr1" {print}' > chr1.bed  #subset chr1
python bin_bed.py chr1.bed 1000000 chr1_1Mb.bed
```
