### ISSUE TITLE
Input and memory issue

### ISSUE THREAD

**Issue by poflawless** [seqcode/miniMDS#27]
Hello Professor,
Thanks for your conribution to the community. I got three questions that can't figure out.

1 how can I generate input files for miniMDS from hicpro output?

2 For the memory, When I run the test data  scripts/hic_data/GM12878_combined_1_5kb.bed, I set memory as 300Gb, but after a few hours later, it raised an error: out of memory. what is the memory size I should put for different Kb resolution? 

3 Is the software including the parameters to save memory and run fast that I didn't notice?

Thanks again for your help.

Best Wishes

**Comment by poflawless** [comment]
Hello Professor,

I got another question. If I  just want to simulate one specific region on the genome, what should I do for the iput and later paramaters?

Thanks again.

Best Wishes,

**Comment by Lila14** [comment]
1: 

`python scripts/hicpro_to_bedpe.py [NAMES BED PATH] [MATRIX PATH] [OUTPUT BED PATH]`


[NAMES BED PATH] is the path to a BED file connecting genomic intervals to names, e.g.


chr1 1 2 A

chr2 1 2 B

chr3 1 2 C


[MATRIX PATH] is the path to a sparse counts matrix file, e.g.


A B 10

A C 23

B C 24


[OUTPUT BED PATH] is the path where the output miniMDS input BED file will be written


2 and 3: 

Use the —partitioned option to reduce memory usage. Selecting a subset of the chromosome as you suggested is also a good idea.

4: 

To select chr1:1Mb-2Mb

`cat scripts/hic_data/GM12878_combined_1_5kb.bed | awk -v lower=1000000 -v upper=2000000 '$2 >=  lower && $2 <= upper && $5 >= lower && $5 <= upper {print $0}' > scripts/hic_data/GM12878_combined-1Mb-2Mb_1_5kb.bed`
