### ISSUE TITLE
HiC data resolution

### ISSUE THREAD

**Issue by jeff-godwin** [seqcode/miniMDS#28]
Hi,
Thanks for the software and the detailed documentation.
This is more of a clarification regarding 3D modeling as a whole (This is my 1st time).
I used my yeast Hic data at 5000 resolution to produce my model.
I'm trying to find out what bearing does resolution have on the model (Is higher better or is there a trade-off)
I have not been able to find much literature. Could you please guide me on this?

Many thanks,
Jeff

**Comment by Lila14** [comment]
At higher resolution the data becomes sparser (more zeros). I think 5kb is reasonable for yeast because it's a small genome. If you're experienced with programming, you could try plotting the percentage of zeros in the count matrix vs resolution. You should see an increase at higher resolution.
