### ISSUE TITLE
minimds_inter cannot handle any chromosome name

### ISSUE THREAD

**Issue by grmwld** [seqcode/miniMDS#3]
https://github.com/seqcode/miniMDS/blob/master/minimds_inter.py#L16

Not all genomes have chromosome names in the form of `chrX`
Maybe this could be done conditionally:

```python
names = [cluster.chrom.name for cluster in clusters]
n = len(names)
for i in range(n):
	if names[i].startswith("chr"):
		names[i] = names[i][3:len(names[i])]	#remove "chr"
```

**Comment by Lila14** [comment]
Good point. I've pushed this.
