### ISSUE TITLE
Conversion to PDB format

### ISSUE THREAD

**Issue by jeff-godwin** [seqcode/miniMDS#34]
Hello,

Is it possible to generate a PDB file from the coordinates?
If so, could you please recommend a particular script?

Many thanks,
Jeff

**Comment by Lila14** [comment]
I've added a script struct_to_pdb.py

```
cd scripts
python struct_to_pdb.py out.pdb scale_factor in_structure.tsv
```

scale_factor is any number to make the spacing look better in a pdb viewer. I used 100 when testing. 

You can also plot multiple structures as different chains in the pdb. (This only makes sense if the structures were generated based on inter-chromosomal interactions.)

`python struct_to_pdb.py out.pdb scale_factor *structure.tsv`
