### ISSUE TITLE
Highlighting regions in the model

### ISSUE THREAD

**Issue by jeff-godwin** [seqcode/miniMDS#35]
Hi,

I have optimized the model and would like to highlight regions in the genome such as centromeres, telomeres.
Also I would like to mark ChIP binding sites. I notice there's a functionality to add ChIP enrichments. But I have
not been able to work out the format of these "enrichment files". 
For the enrichments arguement in "plotting.plot_structure_interactive", I gave a numpy array with - 
bin ID(same as structure TSV) and enrichment score, but it produced the following error -

AssertionError: argument shape are not equal

Could you please guide me on this?

Thank you,
Jeff

**Comment by Lila14** [comment]
The numpy array should only include the nonzero bins. Add the following line
`enrichments = enrichments[structure.nonzero_abs_indices()]`
