### ISSUE TITLE
3D Genome Modeling Using miniMDS

### ISSUE THREAD

**Issue by shenlinyong** [seqcode/miniMDS#36]
I hope this email finds you well. I am writing to express my gratitude for developing the miniMDS software, which has been instrumental in my research on the 3D genome modeling of adipose tissues in chicken breeds. I am currently in the process of submitting my findings to Nature Communications.

During the review process, one of the reviewers raised the following concern regarding Figure 3b in my manuscript:

"Figure 3b: the reconstructed inter-chromosomal 3D genome structures are not biologically realistic. Since the chicken genome is diploid, each chromosome has two copies. For example, there should be two 'chr1'. However, the reconstructed 3D structures appear to only have one copy of each chromosome.

Due to the relatively stable property of intra-chromosomal structures, it is reasonable to reconstruct consensus intra-chromosomal structures based on intra-chromosomal Hi-C contacts (without considering diploids). However, due to the large cell-to-cell variability of inter-chromosomal structures, it is an ill-posed problem of reconstructing consensus inter-chromosomal structures without delineating the two haploids.

Given the significance of this issue, I would greatly appreciate your advice on how to address it using miniMDS. Specifically, I am looking for guidance on the following points:

How can I modify the 3D genome reconstruction process to accurately represent each chromosome as having two copies, in line with the diploid nature of the chicken genome?
Are there specific parameters or methods within miniMDS that can be adjusted to better delineate the two haploids and account for the variability in inter-chromosomal structures?
Any insights or suggestions you could provide would be immensely helpful in refining my manuscript and addressing the reviewer's concerns effectively.

Thank you once again for your invaluable contribution to the field and for your assistance with this matter. I look forward to your response.

**Comment by Lila14** [comment]
You'll need to use a package to analyze diploid Hi-C data. Here's one example: https://link.springer.com/article/10.1186/s12864-020-07165-x

I'm not familiar with this type of analysis so I don't have any recommendations, but you can find a number of similar packages in the literature. 

Then when you use minimds, specify the chromosomes based on their diploid names. For example if the package outputs names like 1A, 1B, use the options -c 1A -c 1B. Custom chromosome naming is described in the readme.
