### ISSUE TITLE
output description

### ISSUE THREAD

**Issue by billgreenwald** [seqcode/miniMDS#5]
Hi,

I am trying to get the 3D positions of different points on each chromosome so that I can calculate the distance between them in 3D space.  I don't need the visualization part of miniMDS, but do need some help understanding the output.  I didn't see a section on it in the README, but I apologize if I missed it.

I ran the test data and added -o test_out.txt so that i could see the output.  It looks like sets of 3D coordinates, but I can't tell how the lines correspond to the positions on the chromosome tested.

My eventual goal is to run this on ~1kb map resolution HiC data.

Thanks!

**Comment by Lila14** [comment]
The output file consists of a header followed by the coordinates. The
header consists of the chromosome name, the resolution of the chromosome,
and the starting genomic bin of the chromosome. The 3D coordinates begin at
the starting genomic bin. For example, if the header is:
chr21
1000000
16000000

then this means that the first 3D coordinate corresponds to the bin
chr21:16,000,000-17,000,000, the second coordinate is
chr21:17,000,000-18,000,000, etc. Some bins are unmappable and are
excluded, so their 3D coordinate is "None". However, they are included in
output for ease of indexing.

**Comment by billgreenwald** [comment]
Thanks!

**Comment by billgreenwald** [comment]
Sorry to reopen so quickly; what kind of normalization needs to be used?  Will KR normalization work fine?

**Comment by Lila14** [comment]
That would be fine. HiC-Pro is a useful pipeline for processing Hi-C data
(starting with fastq files): https://github.com/nservant/HiC-Pro. It uses
ICE normalization, which also works. However, ICE can introduce extreme
outliers, so it's worth double-checking the normalized data before using
it.

**Comment by billgreenwald** [comment]
Thanks!  We used juicebox to process and QC our data, which is why I am utilizing KR normalization.  I appreciate the help and quick responses.
