### ISSUE TITLE
--full option fails in minimds_inter

### ISSUE THREAD

**Issue by ghost** [seqcode/miniMDS#6]
Hi,

I'm trying to constitute 3D structures by using minimds_inter.
When trying to run minimds_inter with --full option, the program was stopped with an error.

```
python minimds_inter.py --full -c 1 -c 2 seg/seg 100000 100000
[...]
  File "minimds_inter.py", line 161, in <module>
    main()
  File "minimds_inter.py", line 151, in main
    structures = interMDS(chrom_names, args.prefix, args.inter_res, args.intra_res, args.full, params)
  File "minimds_inter.py", line 93, in interMDS
    high_structure = mm.fullMDS(path, False, args[4])
TypeError: fullMDS() takes exactly 4 arguments (3 given)
```
When running minimds_inter without --full option, it looks OK.
However, I need to compare the results with or without --full option.

Thanks.

**Comment by Lila14** [comment]
Thanks for spotting this bug. I've added a fix. Let me know if it works now with the latest code.

**Comment by ghost** [comment]
It works! Thanks!!
