### ISSUE TITLE
matFromBed returns empty array

### ISSUE THREAD

**Issue by oluwatosin-oluwadare** [seqcode/miniMDS#7]
I'm trying to use miniMDS with some datasets, and it seems there is a bug when it gets to the matfromBed(*,*) function. I got the error below with all the datasets I tried.

I used the command python minimds.py sample.bed

Traceback (most recent call last):
  File "minimds.py", line 142, in <module>
    main()
  File "minimds.py", line 133, in main
    structure = partitionedMDS(args.path, params)
  File "minimds.py", line 53, in partitionedMDS
    low_contactMat = dt.matFromBed(path, lowstructure)
  File "/storage/htc/bdm/tosin/High_Res_3DGenome/Algorithms/miniMDS/data_tools.py", line 239, in matFromBed
    maxPointNum = max(pointNums)
ValueError: max() arg is an empty sequence

Please find attached  2 data sets I tried. Your quick response will be appreciated
[miniMDS.zip](https://github.com/seqcode/miniMDS/files/1988616/miniMDS.zip)

**Comment by Lila14** [comment]
It looks like your BED files don't quite have the right format. For
example, the first line is:

chr22     16050000     16050000  chr22     16050000     16050000  7483.800

If your data is 10kb resolution, this should be:

chr22     16050000     16060000  chr22     16050000     16060000  7483.800

Please let me know if that fixes the issue.

**Comment by oluwatosin-oluwadare** [comment]
Hi,


sample source data


16840000  16850000   459.590
16850000  16850000  5089.100
16840000  16860000   198.810
16850000  16860000   485.350


I have reformatted my input based on the source data and the data below  is what I have. The data in row 2 and 3 above is not used

Sample Data A

16050000 16060000 2214.10000000000
16060000 16070000 2109.90000000000
16220000 16230000 1231.40000000000
16230000 16240000 676.450000000000
16340000 16350000 1372
16360000 16370000 383.600000000000

'My question now is :

1) what happens to the gaps in row 2 and 3 in sample Data A  as there is no IF recorded for ?

16070000 16080000
16080000 16090000
and so on
2) Is the sample data A above a good input for miniMDS?



Thanks..

**Comment by Lila14** [comment]
Each line should have 7 values in it, as in the example I showed:

chrom bin_start1 bin_end1 chrom bin_start2 bin_end2 IF

Do not enter lines with no IF. (There should be no lines with 0 IF - this
can mess things up.)

**Comment by oluwatosin-oluwadare** [comment]
Please check out my new dataset, it complies with the format but still getting the error:

path = chr22_10kb_miniMDS.bed
[]
number of points = 0
Traceback (most recent call last):
  File "minimds.py", line 142, in <module>
    main()
  File "minimds.py", line 133, in main
    structure = partitionedMDS(args.path, params)
  File "minimds.py", line 53, in partitionedMDS
    low_contactMat = dt.matFromBed(path, lowstructure)
  File "data_tools.py", line 239, in matFromBed
    maxPointNum = max(pointNums)
ValueError: max() arg is an empty sequence

Thanks

[chr22_10kb_miniMDS.zip](https://github.com/seqcode/miniMDS/files/1989001/chr22_10kb_miniMDS.zip)

**Comment by Lila14** [comment]
The format still isn't quite right. All the lines in your file are
self-interactions, like this:

chr22     16050000     16060000  chr22     16050000     16060000  2214.100

This shows that the IF of the 16050000-16060000 bin with itself is
2214.100. Self-interactions are fine, but Hi-C data should have
non-self-interactions, like below:

chr22     16050000     16060000  chr22     16060000     16070000  IF

This is the IF of the 16050000-16060000 bin with the 16060000-16070000 bin.

So I suspect there was some issue in formatting your file.

**Comment by oluwatosin-oluwadare** [comment]
Oh!!!, I know what you mean. Fixed it.

Thanks.
