### ISSUE TITLE
partitionedMDS error

### ISSUE THREAD

**Issue by oluwatosin-oluwadare** [seqcode/miniMDS#8]
Hi, I am getting this error repeatedly, do you know what could be wrong..

Traceback (most recent call last):
  File "minimds.py", line 142, in <module>
    main()
  File "minimds.py", line 133, in main
    structure = partitionedMDS(args.path, params)
  File "minimds.py", line 103, in partitionedMDS
    print "MDS performed on structure {} of {}".format(substructurenum + 1, numSubstructures)
  File "/home/tosin/python/lib/python2.7/site-packages/pymp/__init__.py", line 134, in __exit__
    raise exc_t(exc_val)
AssertionError

Please download one of the data giving this error from the link below:
https://1drv.ms/f/s!AgtbDC-9NW9msMgmYPANpV_ZlE0olA

**Comment by Lila14** [comment]
This was a bug with indexing. I've completely refactored the code and it should be fixed now. Thanks for pointing this out!

I did notice that your structure looked clumpy when I plotted it. Reducing the -p or -m parameters sometimes helps with this. However, 5kb might be too high resolution for how much coverage that dataset has. MiniMDS improves the results of low-coverage high-resolution datasets, but there's only so far it can be pushed. I tried reducing to 20kb and got better results: https://drive.google.com/file/d/1EK3_X2hGL_IG_R8unksrnD1AKge-q5d7/view?usp=sharing

**Comment by oluwatosin-oluwadare** [comment]
Thanks...

________________________________

**Comment by oluwatosin-oluwadare** [comment]
Can you please update the code on your source page, so that I can download the fixed copy. Thanks again.

**Comment by Lila14** [comment]
Sorry, I thought I pushed it. Fixed now.
